# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Kmivo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'YES' if config.name == 'Release'
        config.build_settings['COPY_PHASE_STRIP'] = 'YES' if config.name == 'Release'
        config.build_settings['HERMES_RELEASE_DSYM_GENERATE_SYMBOLS'] = 'YES' if config.name == 'Release'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
      
      # Fix for: call to consteval function 'fmt::basic_format_string' is not a constant expression
      if target.name == 'fmt'
        fmt_base_h = File.join(installer.sandbox.pod_dir('fmt'), 'include', 'fmt', 'base.h')
        if File.exist?(fmt_base_h)
          puts "Patching fmt/base.h to fix consteval error..."
          content = File.read(fmt_base_h)
          # Only patch if it hasn't been patched already
          unless content.include?('// Patched for Xcode consteval error')
            new_content = content.gsub(/^#\s*define FMT_USE_CONSTEVAL 1$/, "#define FMT_USE_CONSTEVAL 0 // Patched for Xcode consteval error")
            File.chmod(0644, fmt_base_h)
            File.write(fmt_base_h, new_content)
          end
        end
      end
    end
  end
end
